// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	models "github.com/faroukelkholy/bank/internal/service/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: t
func (_m *Service) CreateTransaction(t *models.Transfer) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transfer) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
