// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	models "github.com/faroukelkholy/bank/internal/service/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetAccount provides a mock function with given fields: id
func (_m *Service) GetAccount(id string) (*models.Account, error) {
	ret := _m.Called(id)

	var r0 *models.Account
	if rf, ok := ret.Get(0).(func(string) *models.Account); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountTransactions provides a mock function with given fields: id
func (_m *Service) GetAccountTransactions(id string) ([]*models.Transaction, error) {
	ret := _m.Called(id)

	var r0 []*models.Transaction
	if rf, ok := ret.Get(0).(func(string) []*models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
