// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	models "github.com/faroukelkholy/bank/internal/service/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateCustomerAccount provides a mock function with given fields: id, account
func (_m *Service) CreateCustomerAccount(id string, account *models.Account) error {
	ret := _m.Called(id, account)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *models.Account) error); ok {
		r0 = rf(id, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
